### ISSUE TITLE
forking mainnet , using  WETH Gateway exhcange ETH to WETH

### ISSUE THREAD

**Issue by hcmsuper** [PatrickAlphaC/hardhat-defi-fcc#22]
This is my code:
```
const { getNamedAccounts, ethers } = require("hardhat")

const AMOUNT = ethers.utils.parseEther("0.02")


async function getWeth() {
    deployer = await getNamedAccounts()
    // const signer = await ethers.getSigner(deployer)
    
    const iWETHGateway = await ethers.getContractAt(
        "0xEFFC18fC3b7eb8E676dac549E0c693ad50D1Ce31",  //aaveV2 mainnet WETHGateway address 
        abi,
        deployer
    )
    // await iWETHGateway.depositETH()
    console.log(iWETHGateway)
}

module.exports = { getWeth }
```

i got a error: 
```
Error: cannot find artifact "0xEFFC18fC3b7eb8E676dac549E0c693ad50D1Ce31"
    at Object.getArtifact (/root/hh-fcc/hardhat-defi-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:207:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.getContractAt (/root/hh-fcc/hardhat-defi-fcc/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:404:22)
    at getWeth (/root/hh-fcc/hardhat-defi-fcc/scripts/getWeth.js:160:26)
    at main (/root/hh-fcc/hardhat-defi-fcc/scripts/aaveBorrow.js:5:5)
error Command failed with exit code 1.
```

@PatrickAlphaC

**Comment by hcmsuper** [comment]
https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts
![image](https://user-images.githubusercontent.com/61766040/235830269-f2f2775c-ecc7-4fe9-b872-e45fad4ffb52.png)

**Comment by hcmsuper** [comment]
i get it
